[lift]
name = "pikesquares"
description = "PikeSquares App."
load_dotenv = false
# base = "/opt/pike-squares/var/.cache/nce"

[lift.app_info]
repo = "https://github.com/EloquentBits/pikesquares"

[lift.ptex]
id = "ptex"
version = "0.7.0"

[lift.scie_jump]
version = "0.13.3"

[[lift.interpreters]]
id = "cpython311"
provider = "PythonBuildStandalone"
version = "3.11"

[[lift.files]]
name = "pikesquares-bundle"

[[lift.commands]]
name = ""
description = "pikesquares cli"
exe = "{pikesquares-bundle}"
args = []
