[lift]
name = "pikesquares"
description = "PikeSquares App."
load_dotenv = false
# base = "/opt/pike-squares/var/.cache/nce"

[lift.app_info]
repo = "https://github.com/EloquentBits/pikesquares"

[lift.ptex]
id = "ptex"
version = "0.7.0"

[lift.scie_jump]
version = "0.14.0"

[[lift.interpreters]]
id = "cpython312"
provider = "PythonBuildStandalone"
version = "3.12.1"
release = "20240107"

[[lift.files]]
name = "pikesquares-pex"

[[lift.files]]
name = "entrypoint.py"

#[[lift.files]]
#name = "healthchecks-io-pex"
#type = "blob"
#source = { url = "https://pikesquares-downloads.b-cdn.net/healthchecks-io-3-1.pex", lazy = true }
#digest = { size = 18865100, fingerprint = "e1252c97e5e765a2ffb75bc2d4c5ddab8cfa98ef547bb1f39b051380bf013a7c" }
#eager_extract = true

[[lift.commands]]
description = "Launch PikeSquares"
exe = "{pikesquares-pex}"

#[lift.commands.env.default]
#HC_PEX_ROOT = "{scie.bindings.healthchecks}"
#HC_PEX_ROOT = "{scie.bindings.healthchecks:VIRTUAL_ENV}"

#env.remove_re = [
#    "PEX_.*",
#]

#[lift.bindings.env.replace]
#PEX_ROOT = "{scie.bindings}/pex_root"
#PEX_PYTHON_PATH = "#{cpython312:python}"

#[lift.commands.env.replace]
#HC_ROOT = "{scie.file.healthchecks-io-pex}"
#HC_PEX_ROOT = "{scie.bindings.healthchecks}/pex_root"
#SCIE_BINDING_ENV = "/home/pk/dev/eqb/pikesquares/scie_env"
#PEX_ROOT = "{scie.bindings.healthchecks-io}/pex_root"
#PEX_PYTHON_PATH = "#{cpython39:python}"

#[[lift.bindings]]
#name = "healthchecks"
#exe = "#{cpython312:python}"
#args = [
#    "{healthchecks-io-pex}",
#    "{entrypoint.py}",
#]
#env.remove_re = [
#    "PEX_.*",
#]

#[lift.bindings.env.replace]
#PEX_ROOT = "{scie.bindings}/pex_root"
#PEX_PYTHON_PATH = "#{cpython312:python}"
