import sqlmodel

"""uwsgi option sort order index

Revision ID: 0581ec94c011
Revises: 1c8bd2609a23
Create Date: 2025-03-11 13:17:58.813893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0581ec94c011'
down_revision: Union[str, None] = '1c8bd2609a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uwsgi_options', sa.Column('sort_order_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uwsgi_options', 'sort_order_index')
    # ### end Alembic commands ###
