import sqlmodel

"""rm pki_dir from service model

Revision ID: 149459b72db6
Revises: 0581ec94c011
Create Date: 2025-03-11 14:41:53.838301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149459b72db6'
down_revision: Union[str, None] = '0581ec94c011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baserouter', 'pki_dir')
    op.drop_column('device', 'pki_dir')
    op.drop_column('project', 'pki_dir')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('pki_dir', sa.VARCHAR(length=255), nullable=False))
    op.add_column('device', sa.Column('pki_dir', sa.VARCHAR(length=255), nullable=False))
    op.add_column('baserouter', sa.Column('pki_dir', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
