import sqlmodel

"""rm uwsgi_config json field from base service model

Revision ID: 1836bf0d0872
Revises: e68fe2672245
Create Date: 2025-04-07 09:44:53.867469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1836bf0d0872'
down_revision: Union[str, None] = 'e68fe2672245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baserouter', 'uwsgi_config')
    op.drop_column('device', 'uwsgi_config')
    op.drop_column('project', 'uwsgi_config')
    op.drop_column('wsgiapp', 'uwsgi_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wsgiapp', sa.Column('uwsgi_config', sqlite.JSON(), nullable=True))
    op.add_column('project', sa.Column('uwsgi_config', sqlite.JSON(), nullable=True))
    op.add_column('device', sa.Column('uwsgi_config', sqlite.JSON(), nullable=True))
    op.add_column('baserouter', sa.Column('uwsgi_config', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
