import sqlmodel
"""init

Revision ID: 1d78b88076ce
Revises: 
Create Date: 2025-03-09 10:04:15.207679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d78b88076ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('service_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uwsgi_config', sa.JSON(), nullable=True),
    sa.Column('data_dir', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('log_dir', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('config_dir', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('run_dir', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('pki_dir', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sentry_dsn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cert_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('machine_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('server_run_as_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('server_run_as_gid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id'),
    sa.UniqueConstraint('service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    # ### end Alembic commands ###
