import sqlmodel
"""service stores uwsgi plugins

Revision ID: 8837a1efe731
Revises: d0e166d5331b
Create Date: 2025-03-10 08:21:49.534643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8837a1efe731'
down_revision: Union[str, None] = 'd0e166d5331b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('baserouter', 'uwsgi_plugins',
    #           existing_type=sa.VARCHAR(length=255),
    #           nullable=True)
    op.add_column('baserouter', sa.Column('uwsgi_plugins', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('device', sa.Column('uwsgi_plugins', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('project', sa.Column('uwsgi_plugins', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'uwsgi_plugins')
    op.drop_column('device', 'uwsgi_plugins')
    op.drop_column('baserouter', 'uwsgi_plugins')
    #op.alter_column('baserouter', 'uwsgi_plugins',
    #           existing_type=sa.VARCHAR(length=255),
    #           nullable=False)
    # ### end Alembic commands ###
