import sqlmodel
"""projects table run as uid, gid

Revision ID: e2534dde880f
Revises: b278c6ba6726
Create Date: 2025-03-09 10:48:23.178678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2534dde880f'
down_revision: Union[str, None] = 'b278c6ba6726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('run_as_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('project', sa.Column('run_as_gid', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'run_as_gid')
    op.drop_column('project', 'run_as_uid')
    # ### end Alembic commands ###
