name: build-macos-pkg-installer-workflow

on:
  workflow_run:
    workflows: ["build-publish-multiplatform-binary-workflow"]
    types:
      - completed
  # workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #   tags:
  #     - '**'
  
jobs:
  build-macos-pkg-installer:
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]
        platform: [ macos-latest-arm64 ] # macos-latest-large - intel, macos-latest-xlarge - apple silicon
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install -U jinja2
      
      - name: Checkout pikesquares Mac OS Installer Builder (MIB) repo
        uses: actions/checkout@v4
        with:
          repository: EloquentBits/pikesquares-mib
          path: mib

      - name: Run Mac OS Installer Builder (MIB)
        shell: bash
        run: |
          cd mib
          python mib.py --config mib.toml

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: pikesquares-installer
            path: pikesquares-installer.pkg
