name: build-and-release-pikesquares

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '**'
    paths-ignore:
      - '**.md'
      - 'scripts/**'
      - 'tests/**'
      - '.github/workflows/**'
      - '!.github/workflows/build.yml'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:

  wheels:
    name: "${{ matrix.py }} ${{ matrix.os }} ${{ matrix.arch }} wheels"
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        os: [ubuntu, macos]
        arch: [x86_64]
        include:
          - {
              "os": "ubuntu", 
              "py": "cp311", 
              "arch": "x86_64", 
              "runner": "ubuntu-latest", 
              "pikesquares-binary-version": "0.3.22",
              "cibw_build": "cp311-manylinux_x86_64", 
              "cibw_wheel_suffix": "manylinux_2_17_x86_64.manylinux2014_x86_64",
              "pip-cache-path": "~/.cache/pip" }
          - {
              "os": "macos", 
              "py": "cp311", 
              "arch": "x86_64", 
              "runner": "macos-latest", 
              "pikesquares-binary-version": "0.3.22",
              "cibw_build": "cp311-macosx_x86_64", 
              "cibw_wheel_suffix": "macosx_10_9_x86_6",
              "pip-cache-path": "~/Library/Caches/pip" }

          #- {"os": "macos", "py": "cp311", "arch": "arm64", "runner": "macos-latest-xlarge", "cibw_build": "cp311-macosx_arm64",  "pip-cache-path": "~/Library/Caches/pip"}
      fail-fast: false

    env:
      MATRIX_ID: "${{ matrix.py }}-${{ matrix.os }}-${{ matrix.arch }}"
      CIBW_BUILD: "${{ matrix.cibw_build }}"
      CIBW_ARCHS: ${{ matrix.arch }}
      CIBW_BUILD_VERBOSITY: 5
      CIBW_ENVIRONMENT: APPEND_VERSION=".post0" UWSGI_PROFILE=pikesquares
      CIBW_BEFORE_ALL: ./scripts/patch-uwsgi-packaging.sh uwsgi
      CIBW_BEFORE_BUILD_LINUX: yum install -y openssl-devel zlib-devel zeromq-devel libsqlite3x-devel.x86_64 pcre-devel jansson-devel 
      CIBW_BEFORE_BUILD_MACOS: IS_MACOS=1 ARCH=${{ matrix.arch }} ./scripts/pre_build.sh
      CIBW_MANYLINUX_X86_64_IMAGE: "manylinux2014"

    steps:
      - name: install deps from homebrew
        if: ${{ matrix.os == 'macos' && matrix.arch == 'x86_64'}}
        shell: bash
        run: |
          brew install zeromq jansson pcre

      - name: install deps from homebrew
        if: ${{ matrix.os == 'macos' && matrix.arch == 'arm64'}}
        shell: bash
        run: |
          brew install zeromq jansson pcre autoconf libtool automake

      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: actions/cache@v3
        name: pip cache
        with:
          path: ${{ matrix.pip-cache-path }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
           ${{ runner.os }}-pip-

      #pikesquares_binary-0.3.22-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
      #pikesquares_binary-0.3.22-cp311-cp311-macosx_10_9_x86_64.whl
      - uses: actions/cache@v3
        id: pikesquares-binary-wheel
        name: cache wheel
        with:
          path: wheelhouse/pikesquares_binary-${{ matrix.pikesquares-binary-version }}-cp311-cp311-${{ matrix.cibw_wheel_suffix }}.whl
          key: ${{ runner.os }}-pikesquares_binary-${{ matrix.pikesquares-binary-version }}-${{ matrix.cibw_wheel_suffix }}

      - name: install cibuildwheel
        shell: bash
        run: |
          pip install 'cibuildwheel>=2.16.2' twine build

      - name: setup Ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}-${{ matrix.arch }}-${{ matrix.py }}
          #save: ${{ github.ref == 'refs/heads/main' || github.repository != 'duckdb/duckdb' }}

      # macos-latest Version: 10.9
      # pyuwsgi.cpython-311-darwin.so
      - name: build wheel
        if: ${{ steps.pikesquares-binary-wheel.outputs.cache-hit != 'true' }} 
        shell: bash
        run: |
          export DISTUTILS_C_COMPILER_LAUNCHER=ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          # TODO: Use ccache inside container, see https://github.com/pypa/cibuildwheel/issues/1030
          #if [[ "$GITHUB_REF" =~ ^refs/tags/v.+$ ]] ; then
          #  export CIBW_TEST_COMMAND='python -m pytest {project}/tests/fast/api/test_dbapi00.py  --verbose'
          #fi
          cibuildwheel --output-dir wheelhouse uwsgi
          ls wheelhouse

      #pikesquares_binary-0.3.22-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
      #pikesquares_binary-0.3.22-cp311-cp311-macosx_10_9_x86_64.whl
      #
      #- uses: actions/upload-artifact@v4
      #  if: false
      #  with:
      #    name: pikesquares-binary-cp311-manylinux_x86_64
      #    path: ./wheelhouse/*.whl
