name: build-and-release-pikesquares

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '**'
    paths-ignore:
      - '**.md'
      - 'scripts/**'
      - 'tests/**'
      - '.github/workflows/**'
      - '!.github/workflows/build.yml'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:

  wheels:
    name: "${{ matrix.py }} ${{ matrix.os }} ${{ matrix.arch }} wheels"
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        os: [linux, macos]
        arch: [x86_64, arm64]
        include:
          - {
              "os": "linux", 
              "py": "cp311", 
              "arch": "x86_64", 
              "runner": "ubuntu-latest", 
              "cibw_build": "cp311-manylinux_x86_64", 
              "cibw_wheel_suffix": "manylinux_2_17_x86_64.manylinux2014_x86_64",
              "pip-cache-path": "~/.cache/pip" }
          - {
              "os": "macos", 
              "py": "cp311", 
              "arch": "x86_64", 
              "runner": "macos-latest", 
              "cibw_build": "cp311-macosx_x86_64", 
              "cibw_wheel_suffix": "macosx_10_9_x86_64",
              "pip-cache-path": "~/Library/Caches/pip" }

          - {
              "os": "macos", 
              "py": "cp311", 
              "arch": "arm64", 
              "runner": "macos-latest-xlarge", 
              "cibw_build": "cp311-macosx_arm64",  
              "cibw_wheel_suffix": "macosx_11_0_arm64",
              "pip-cache-path": "~/Library/Caches/pip"}
        exclude:
          - os: linux
            arch: arm64

          #- {"os": "macos", "py": "cp311", "arch": "arm64", "runner": "macos-latest-xlarge", "cibw_build": "cp311-macosx_arm64",  "pip-cache-path": "~/Library/Caches/pip"}
      fail-fast: false

    env:
      MATRIX_ID: "${{ matrix.py }}-${{ matrix.os }}-${{ matrix.arch }}"
      SCIENCE_BINARY_VERSION: "v0.3.0"
      PIKESQUARES_BINARY_VERSION: "0.3.22"
      PIKESQUARES_CLI_VERSION: "0.1.6"

      CIBW_BUILD: "${{ matrix.cibw_build }}"
      CIBW_ARCHS: ${{ matrix.arch }}
      CIBW_BUILD_VERBOSITY: 5
      CIBW_ENVIRONMENT: APPEND_VERSION=".post0" UWSGI_PROFILE=pikesquares
      CIBW_BEFORE_ALL: ./scripts/patch-uwsgi-packaging.sh uwsgi
      CIBW_BEFORE_BUILD_LINUX: yum install -y openssl-devel zlib-devel zeromq-devel libsqlite3x-devel.x86_64 pcre-devel jansson-devel 
      CIBW_BEFORE_BUILD_MACOS: IS_MACOS=1 ARCH=${{ matrix.arch }} ./scripts/pre_build.sh
      CIBW_MANYLINUX_X86_64_IMAGE: "manylinux2014"

    steps:
      - name: install deps from homebrew for x86_64
        if: ${{ matrix.os == 'macos' && matrix.arch == 'x86_64'}}
        shell: bash
        run: |
          brew install zeromq jansson pcre

      - name: install deps from homebrew for arm64
        if: ${{ matrix.os == 'macos' && matrix.arch == 'arm64'}}
        shell: bash
        run: |
          brew install autoconf libtool automake jansson pcre

      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: actions/cache@v3
        name: pip cache
        with:
          path: ${{ matrix.pip-cache-path }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
           ${{ runner.os }}-pip-

      #pikesquares_binary-0.3.22-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
      #pikesquares_binary-0.3.22-cp311-cp311-macosx_10_9_x86_64.whl
      - uses: actions/cache@v3
        id: pikesquares-binary-wheel
        name: cache wheel
        with:
          path: wheelhouse/pikesquares_binary-${{ env.PIKESQUARES_BINARY_VERSION }}-cp311-cp311-${{ matrix.cibw_wheel_suffix }}.whl
          key: pikesquares_binary-${{ env.PIKESQUARES_BINARY_VERSION }}-${{ runner.os }}-${{ matrix.arch }}

      - uses: actions/cache@v3
        id: science-binary
        name: cache science binary
        with:
          path: science
          key: ${{ runner.os }}-science-${{ env.SCIENCE_BINARY_VERSION }}-${{ matrix.arch }}

      - name: install cibuildwheel
        shell: bash
        run: |
          pip install 'cibuildwheel>=2.16.2' twine build

      - name: setup Ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}-${matrix.os}-${{ matrix.arch }}-${{ matrix.py }}

      # macos-latest Version: 10.9
      # pyuwsgi.cpython-311-darwin.so
      - name: build wheel
        if: ${{ steps.pikesquares-binary-wheel.outputs.cache-hit != 'true' }} 
        shell: bash
        run: |
          export DISTUTILS_C_COMPILER_LAUNCHER=ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          # TODO: Use ccache inside container, see https://github.com/pypa/cibuildwheel/issues/1030
          #if [[ "$GITHUB_REF" =~ ^refs/tags/v.+$ ]] ; then
          #  export CIBW_TEST_COMMAND='python -m pytest {project}/tests/fast/api/test_dbapi00.py  --verbose'
          #fi
          cibuildwheel --output-dir wheelhouse uwsgi
          ls wheelhouse

      # Xcode_14.3.1

      #  *** Installing runtime libraries
      #  install libcrypto.3.dylib -> /usr/local/lib/libcrypto.3.dylib
      #  install libssl.3.dylib -> /usr/local/lib/libssl.3.dylib
      #  *** Installing development files
      #  created directory `/usr/local/include/openssl'
      #
      #     install libcrypto.a -> /usr/local/lib/libcrypto.a
      #  install libssl.a -> /usr/local/lib/libssl.a
      #  link /usr/local/lib/libcrypto.dylib -> /usr/local/lib/libcrypto.3.dylib
      #  link /usr/local/lib/libssl.dylib -> /usr/local/lib/libssl.3.dylib
      #  install libcrypto.pc -> /usr/local/lib/pkgconfig/libcrypto.pc
      #  install openssl.pc -> /usr/local/lib/pkgconfig/openssl.pckk
      #  install libssl.pc -> /usr/local/lib/pkgconfig/libssl.pc

      #pikesquares_binary-0.3.22-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
      #pikesquares_binary-0.3.22-cp311-cp311-macosx_10_9_x86_64.whl
      #
      #- uses: actions/upload-artifact@v4
      #  if: false
      #  with:
      #    name: pikesquares-binary-cp311-manylinux_x86_64
      #    path: ./wheelhouse/*.whl
      #
      #
      - name: build pikesquares-cli wheel
        shell: bash
        run: |
          python -m build . --wheel
          ls -l dist

      - name: install pex
        shell: bash
        run: |
          pip install pex

      - name: build pex
        shell: bash

        run: |
          zipinfo wheelhouse/pikesquares_binary-${{ env.PIKESQUARES_BINARY_VERSION }}-cp311-cp311-${{ matrix.cibw_wheel_suffix }}.whl
          pex \
            wheelhouse/pikesquares_binary-${{ env.PIKESQUARES_BINARY_VERSION }}-cp311-cp311-${{ matrix.cibw_wheel_suffix }}.whl \
            dist/pikesquares-${{ env.PIKESQUARES_CLI_VERSION }}-py3-none-any.whl \
            -r requirements.txt \
            --venv \
            --python $(which python) \
            --entry-point pikesquares.cli.cli:app \
            --disable-cache \
            --no-emit-warnings \
            -o pikesquares-cli-${{ matrix.os }}-${{ matrix.arch }}.pex

        #zipinfo pikesquares-cli-${{ matrix.os }}-${{ matrix.arch }}.pex

      #https://github.com/a-scie/jump/releases/download/v0.14.0/scie-jump-linux-x86_64
      #- name: scie-jump binary download
      #  if: ${{ steps.scie-jump-binary.outputs.cache-hit != 'true' }} 
      #  shell: bash
      #  run: |
      #    curl -Lo "sci-jump" https://github.com/a-scie/jump/releases/download/${{ env.JUMP_BINARY_VERSION }}/sci-jupm-${{ runner.os }}-${{ matrix.arch }}
      #    chmod +x science

      - name: science binary download
        if: ${{ steps.science-binary.outputs.cache-hit != 'true' }} 
        shell: bash
        run: |
          curl -Lo "science" https://github.com/a-scie/lift/releases/download/${{ env.SCIENCE_BINARY_VERSION }}/science-${{ runner.os }}-${{ matrix.arch }}
          chmod +x science

      - name: build scie
        shell: bash
        run: |
          ls -l . 
          ./science --version
          ./science lift \
            --file pikesquares-bundle=pikesquares-cli-${{ matrix.os }}-${{ matrix.arch }}.pex \
            build \
            --use-platform-suffix \
            --hash sha256 \
            pikesquares.toml 
          ls -l . 
          chmod 755 pikesquares-${{ matrix.os }}-${{ matrix.arch }}
          ./pikesquares-${{ matrix.os }}-${{ matrix.arch }} --version
        #  linux-aarch64
        #  linux-x86_64
        #  macos-aarch64
        #  macos-x86_64
        #  windows-x86_64

      # /home/runner/work/pikesquares2/pikesquares2/pikesquares-linux-x86_64
      # /home/runner/work/pikesquares2/pikesquares2/pikesquares-linux-x86_64.sha256
      #- uses: actions/upload-artifact@v4
      #  with:
      #    name: pikesquares-${{ matrix.os }}-${{ matrix.arch }}
      #    path: pikesquares-${{ matrix.os }}-${{ matrix.arch }}*

      - name: Publish binary to BunnyCDN
        shell: bash
        env:
          CDN_URL: ny.storage.bunnycdn.com
          CDN_PROJECT_NAME: pikesquares-downloads
        run: |
            curl --request PUT \
            --header 'AccessKey: ${{ secrets.BUNNYCDN_ACCESS_TOKEN }}' \
            --header 'Content-Type: application/octet-stream' \
            --header 'accept: application/json'  \
            --data-binary @pikesquares-${{ matrix.os }}-${{ matrix.arch }} \
            https://${{ env.CDN_URL }}/${{ env.CDN_PROJECT_NAME }}/${{ env.PIKESQUARES_CLI_VERSION }}/pikesquares-${{ matrix.os }}-${{ matrix.arch }}

          #https://github.com/a-scie/lift/releases/download/v0.3.0/science-linux-x86_64
