name: Build binary (multiplatform) and publish it on CDN

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '**'


jobs:
  build-and-publish-binary:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest-arm64 ] # macos-latest-large - intel, macos-latest-xlarge - apple silicon
        architecture: [ x86_64, aarch64 ]
        python-version: [ "3.11", "3.12" ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install -U build pex


      - name: Build CLI wheel
        shell: bash
        run: |
          python -m build . --wheel

      - name: Build PEX
        shell: bash
        env:
          PEX_TOOLS: 1
        run: |
          pex -vvv \
            dist/pikesquares-* \
            -r requirements.txt \
            --venv \
            --include-tools \
            --python $(which python) \
            --entry-point pikesquares.cli.cli:app \
            --disable-cache \
            --no-emit-warnings \
            -o pikesquares-cli.pex
        
      - name: Build executable binary (science) - linux
        shell: bash
        if: runner.os == 'Linux'
        env:
          PLATFORM: "linux"
        run: |
          curl -Lo "science" https://github.com/a-scie/lift/releases/download/latest/science-${{ env.PLATFORM }}-${{ matrix.architecture }}
          chmod +x science
          science lift \
            --file pikesquares=pikesquares-cli.pex build \
            --use-platform-suffix \
            --hash sha256 \
            pikesquares.toml
      
      - name: Build executable binary (science) - Mac OS
        shell: bash
        if: runner.os == 'macOS'
        env:
          PLATFORM: "macos"
        run: |
          curl -Lo "science" https://github.com/a-scie/lift/releases/download/latest/science-${{ env.PLATFORM }}-${{ matrix.architecture }}
          chmod +x science
          science lift \
            --file pikesquares=pikesquares-cli.pex build \
            --use-platform-suffix \
            --hash sha256 \
            pikesquares.toml
      
      - name: Publish binary to cdn - Linux
        shell: bash
        if: runner.os == 'Linux'
        env:
          PLATFORM: "linux"
        run: |
            curl --request PUT \
            --header 'AccessKey: ${{ secrets.CDN_ACCESS_TOKEN }}' \
            --header 'Content-Type: application/octet-stream' \
            --header 'accept: application/json'  \
            --data-binary @pikesquares-${{ env.PLATFORM }}-${{ matrix.architecture }} \
            https://${{ secrets.CDN_URL }}/${{ secrets.CDN_PROJECT_NAME }}/pikesquares-${{ env.PLATFORM }}-${{ matrix.architecture }}

      - name: Publish binary to cdn - Mac OS
        shell: bash
        if: runner.os == 'macOS'
        env:
          PLATFORM: "macos"
        run: |
            curl --request PUT \
            --header 'AccessKey: ${{ secrets.CDN_ACCESS_TOKEN }}' \
            --header 'Content-Type: application/octet-stream' \
            --header 'accept: application/json'  \
            --data-binary @pikesquares-${{ env.PLATFORM }}-${{ matrix.architecture }} \
            https://${{ secrets.CDN_URL }}/${{ secrets.CDN_PROJECT_NAME }}/pikesquares-${{ env.PLATFORM }}-${{ matrix.architecture }}
