name: Publish binary on CDN

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '**'

jobs:
  build-binary:
    strategy:
      matrix:
        os: [ linux, macos ]
        architecture: [ x86_64, aarch64 ]
        python-version: [ "3.11", "3.12" ]
        platform: [ ubuntu-latest, macos-latest-arm64 ] # macos-latest-large - intel, macos-latest-xlarge - apple silicon
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish
        shell: bash
        run: |
            curl --request PUT \
            --header 'AccessKey: ${{ secrets.CDN_ACCESS_TOKEN }}' \
            --header 'Content-Type: application/octet-stream' \
            --header 'accept: application/json'  \
            --data-binary @pikesquares-${{ matrix.os }}-${{ matrix.architecture }} \
            https://${{ secrets.CDN_URL }}/${{ secrets.CDN_PROJECT_NAME }}/pikesquares-${{ matrix.os }}-${{ matrix.architecture }}
