name: Publish binary on CDN

on: [ workflow_dispatch, pull_request ]

jobs:
  build-binary:
    strategy:
      matrix:
        os: [ linux, macos ]
        architecture: [ x86_64, aarch64 ]
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
        platform: [ ubuntu-latest, macos-latest-large, macos-latest-xlarge ] # xlarge - macos with apple silicon processor
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish
        shell: bash
        run: |
            curl --request PUT \
            --header 'AccessKey: ${{ secrets.CDN_ACCESS_TOKEN }}' \
            --header 'Content-Type: application/octet-stream' \
            --header 'accept: application/json'  \
            --data-binary @pikesquares-${{ matrix.os }}-${{ matrix.architecture }} \
            https://${{ secrets.CDN_URL }}/${{ secrets.CDN_PROJECT_NAME }}/pikesquares-${{ matrix.os }}-${{ matrix.architecture }}
